### ISSUE TITLE
Distributed Cell profiler on AWS EKS

### ISSUE THREAD

**Issue by mc35792** [CellProfiler/Distributed-CellProfiler#113]
Hi Team,

How can I get started with using Distributed Cell profiler on AWS EKS cluster if its possible?

**Comment by bethac07** [comment]
We haven't set up DCP to run on EKS, only ECS- it's formally possible it would work, but our team likely won't have time to look into how to set up configuration.

If you do end up investigating it, I'd be curious to learn anything you discover- we're not uninterested in supporting it, just don't have time to build the infrastructure ourselves right now.  

Sorry!
