### ISSUE TITLE
Fix docs: description for setting up IamFleetRole is outdated

### ISSUE THREAD

**Issue by shntnu** [CellProfiler/Distributed-CellProfiler#85]
@mwawer reported that when he tried to run jobs, it fails with:
SpotFleetRequestConfig.IamFleetRole is invalid

and later reported that he had to select different role settings; the description of how to set up that role is  outdated.

**Comment by mwawer** [comment]
This is mainly an issue with the detailed PDF instructions (by John McLaughlin).

When setting up the role, users should select "EC2" from the extended table (NOT the top):
![aws_spot_fleet_role1](https://user-images.githubusercontent.com/3934803/47666468-fbfd3000-db79-11e8-8b5c-d9c217760958.png)

From the detailed options that appear, select "EC2 Spot Fleet Role" and click "Next: Permissions".

Under Permissions, select "AmazonEC2SpotFleetTaggingRole" (the only one available), then review and finish. (I later added "AmazonS3FullAccess", but this may not be necessary).

Once the role is created, it should list spotfleet.amazonaws.com (not ec2.amazonaws.com) under the Trust relationships tab.

**Comment by NiklasTR** [comment]
I had exactly the same problem when I set up DCP 10 days ago. Fixed it the same way.
